"""Set up Alpecca's stable Cloudflare named tunnel.

Quick tunnels are useful for tests but they can disappear or fail to issue a
URL. This script prepares a named tunnel config that always routes the same
public hostname to the same local Alpecca instance on port 8765.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import config  # noqa: E402
from alpecca import preview  # noqa: E402


def run(args: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, text=True, capture_output=True, check=check)


def cloudflared() -> str:
    exe = preview.find_cloudflared()
    if not exe:
        raise SystemExit(
            "cloudflared was not found. Install it first, then rerun this script:\n"
            "  winget install cloudflare.cloudflared"
        )
    return exe


def origin_cert_exists() -> bool:
    if os.environ.get("TUNNEL_ORIGIN_CERT"):
        return Path(os.environ["TUNNEL_ORIGIN_CERT"]).exists()
    for root in (Path.home() / ".cloudflared", Path.home() / ".cloudflare-warp", Path.home() / "cloudflare-warp"):
        if (root / "cert.pem").exists():
            return True
    return False


def safe_hostname(value: str) -> str:
    host = value.strip().replace("https://", "").replace("http://", "").strip("/")
    if not re.match(r"^[a-z0-9][a-z0-9.-]*[a-z0-9]$", host, re.IGNORECASE):
        raise SystemExit(f"Invalid hostname: {value!r}")
    return host.lower()


def find_credentials(tunnel_name: str, output: str, config_dir: Path, tunnel_id: str = "") -> tuple[str, Path]:
    match = re.search(r"([0-9a-fA-F-]{32,})", output)
    tunnel_id = tunnel_id or (match.group(1) if match else "")
    candidates = []
    for folder in (Path.home() / ".cloudflared", config_dir):
        if folder.exists():
            candidates.extend(folder.glob("*.json"))
    if tunnel_id:
        for item in candidates:
            if item.stem.lower() == tunnel_id.lower():
                return tunnel_id, item
    if len(candidates) == 1:
        return candidates[0].stem, candidates[0]
    named = [item for item in candidates if tunnel_name.lower() in item.name.lower()]
    if named:
        return named[0].stem, named[0]
    raise SystemExit(
        "Cloudflare created/listed a tunnel, but I could not find its credentials JSON. "
        "Check ~/.cloudflared and rerun with --credentials-file."
    )


def existing_tunnel_id(exe: str, tunnel_name: str) -> str:
    result = run([exe, "tunnel", "list"], check=False)
    text = (result.stdout or "") + "\n" + (result.stderr or "")
    for line in text.splitlines():
        if tunnel_name.lower() in line.lower():
            match = re.search(r"([0-9a-fA-F-]{32,})", line)
            if match:
                return match.group(1)
    return ""


def write_config(path: Path, tunnel_id_or_name: str, credentials_file: Path, hostname: str, port: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f"""# Alpecca stable Cloudflare tunnel.
# Generated by scripts/setup_cloudflare_tunnel.py.
tunnel: {tunnel_id_or_name}
credentials-file: {credentials_file}

ingress:
  - hostname: {hostname}
    service: http://localhost:{port}
  - service: http_status:404
"""
    path.write_text(text, encoding="utf-8")


def write_env_hint(hostname: str, tunnel_name: str, cfg: Path) -> None:
    env_path = config.HOME / "cloudflared" / "alpecca-cloudflare.env"
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text(
        "\n".join(
            [
                f"ALPECCA_PUBLIC_URL=https://{hostname}",
                f"ALPECCA_CLOUDFLARE_HOSTNAME={hostname}",
                f"ALPECCA_CLOUDFLARE_TUNNEL={tunnel_name}",
                f"ALPECCA_CLOUDFLARE_CONFIG={cfg}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Create/update Alpecca's named Cloudflare tunnel config.")
    parser.add_argument("--hostname", default=config.CLOUDFLARE_HOSTNAME or os.environ.get("ALPECCA_PUBLIC_HOSTNAME", ""))
    parser.add_argument("--name", default=config.CLOUDFLARE_TUNNEL_NAME)
    parser.add_argument("--port", type=int, default=config.PORT)
    parser.add_argument("--config", type=Path, default=config.CLOUDFLARE_CONFIG)
    parser.add_argument("--credentials-file", type=Path, default=None)
    parser.add_argument("--no-route", action="store_true", help="Skip cloudflared tunnel route dns.")
    args = parser.parse_args()

    if not args.hostname:
        raise SystemExit(
            "A stable Cloudflare tunnel needs a hostname on a domain in your Cloudflare account.\n"
            "Example:\n"
            "  python scripts\\setup_cloudflare_tunnel.py --hostname alpecca.example.com"
        )

    hostname = safe_hostname(args.hostname)
    exe = cloudflared()
    if not origin_cert_exists():
        raise SystemExit(
            "Cloudflare login is not configured on this PC yet.\n"
            "Run this once, complete the browser login, then rerun setup:\n"
            f"  \"{exe}\" tunnel login"
        )

    tunnel_id = existing_tunnel_id(exe, args.name)
    create_output = ""
    if tunnel_id:
        print(f"Reusing Cloudflare tunnel {args.name} ({tunnel_id}).")
    else:
        created = run([exe, "tunnel", "create", args.name])
        create_output = (created.stdout or "") + "\n" + (created.stderr or "")
        print(create_output.strip())

    if args.credentials_file:
        credentials_file = args.credentials_file
        tunnel_id_or_name = tunnel_id or args.name
    else:
        tunnel_id_or_name, credentials_file = find_credentials(args.name, create_output, args.config.parent, tunnel_id)

    write_config(args.config, tunnel_id_or_name, credentials_file, hostname, args.port)
    write_env_hint(hostname, args.name, args.config)

    if not args.no_route:
        routed = run([exe, "tunnel", "route", "dns", args.name, hostname], check=False)
        route_text = ((routed.stdout or "") + "\n" + (routed.stderr or "")).strip()
        if routed.returncode == 0:
            print(route_text)
        else:
            print(route_text)
            print("DNS route failed. If the record already exists, this may be harmless.")

    preview.write_state(f"https://{hostname}", args.port, provider="cloudflare-named")
    print("\nStable Alpecca preview configured:")
    print(" ", preview.with_access_token(f"https://{hostname}/house-hq"))
    print("\nRun the tunnel with:")
    print("  python scripts\\run_cloudflare_tunnel.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
